*&---------------------------------------------------------------------*
*& Include          YCL106_002_TOP
*&---------------------------------------------------------------------*
TABLES SCARR.

DATA: OK_CODE TYPE SY-UCOMM,
      SAVE_OK TYPE SY-UCOMM.

DATA: GT_SCARR TYPE TABLE OF SCARR.

SELECTION-SCREEN BEGIN OF SCREEN 0101 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME TITLE TEXT-T01.

*    SELECT-OPTIONS S_CARRID FOR SCARR-CARRID.
*    SELECT-OPTIONS S_CARRNM FOR SCARR-CARRNAME.
*
*    SELECTION-SCREEN PUSHBUTTON 77(10) TEXT-L01 USER-COMMAND SEARCH.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(10) TEXT-L02 FOR FIELD S_CARRID.
      SELECT-OPTIONS S_CARRID FOR SCARR-CARRID.
    SELECTION-SCREEN END OF LINE.

    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN COMMENT 1(10) TEXT-L03 FOR FIELD S_CARRNM.
      SELECT-OPTIONS S_CARRNM FOR SCARR-CARRNAME.
      SELECTION-SCREEN PUSHBUTTON 77(10) TEXT-L01 USER-COMMAND SEARCH.
    SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK B01.
SELECTION-SCREEN END OF SCREEN 0101.
